server:
  port: 8282 
spring:
  security:
    user:
      name: ahmed
      password: 123
      roles: ADMIN,USER

security:
  oauth2:
    client:
      client-id: vue
      client-secret: pin
      access-token-validity-seconds: 3600
      authorized-grant-types: CLIENT_CREDENTIALS,PASSWORD,AUTHORIZATION_CODE,REFRESH_TOKEN
      scope: READ,WRITE
